/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAkan } from "./IAkan";
export type { IERC20 } from "./IERC20";
export type { IUniswapV2Router } from "./IUniswapV2Router";
